### ISSUE TITLE
Any chance to change the Keywords

### ISSUE THREAD

**Issue by mady143** [ongteckwu/Resume-Rater#2]
Hi @ongteckwu ,
                           Its very helpful for me to rate the resumes but i want to know that any change in the fixed keywords as you mentioned in the code as 
r.train(
        "/Users/teckwuong/coderoom/datasets/Resume&Job_Description/Original_Resumes",
        "fixed",
        keywords=["assets", "fund", "investment", "accounting", "trust", "strategy"],
    )
can i change the keywords and path you have in the above line can you explain me clearly 

Thanks and Regards,
Manikantha Sekhar..

**Comment by ongteckwu** [comment]
You can change them to any keywords you want.

**Comment by mmusunur** [comment]
Okay @ongteckwu  and thank you and what is the use of these key words ,
** I had a another doubt i trained with supervised and unsupervised and later i tested with my resume in my resume i mentioned as work experience as 1 year 8 months but while doing test in the console i am getting only 5 months how it is considering the experience 
** Is their any format(inside the context of the  resume ) fro testing the resume or it will takes any format 
Thank you ,
Manikantha Sekhar.

**Comment by ongteckwu** [comment]
Keywords are what u r looking for in a person. 
It takes any format, but in general it can still be wrong about work experience since it’s a prototype for an interview.

**Comment by mmusunur** [comment]
Okay @ongteckwu  and thank you so much for your patience for the reply
i had successfully run the code and can i differentiate the Declaration , Address and tools sections which i had used in my project and where can i change the code for to divide the sections 

Thanks and Regards,
Manikantha Sekhar..
